name: Daily Python Script

on:
  schedule:
    - cron: "* * * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Specify your desired Python version
          
      - name: Install dependencies
        run: pip install -r requirements.txt  # If you have any dependencies, specify them in requirements.txt
        
      - name: Run Python script
        run: python your_script.py  # Replace 'your_script.py' with the filename of your Python script
